# Generated by Django 3.2.14 on 2022-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
